### ISSUE TITLE
Too many redirects issue

### ISSUE THREAD

**Issue by pmspire** [LassoProject/lasso#42]
I looked through what appear to be related (closed) issues, but was not able to find a solution to my problem. I hope you can help.

I have Lasso (compiled binary, not docker container) running on one host, proxied behind NGINX with SSL, with its own hostname (`lasso.[domain].com`). I have a basic NGINX static site for testing with Lasso, running on a separate host, with its own hostname (`foo.[domain].com`), also with SSL. I've tried to follow several guides for configuring both NGINX and Lasso. Here's what I see:

When I hit the static site in Chrome, I'm redirected to the Google "Sign in" page. In my static site's NGINX `access.log`, I see the expected 302 redirect to Lasso; Lasso shows `no jwt found in request`, a 401 from `/validate`, then a 302 from `/login`. Back in the browser, I enter my email address and password (I've got `allowAllUsers: true` in my Lasso `config.yml`, along with a whitelist specifying my email address). My address bar shows `https://accounts.youtube.com/accounts/SetSID` for a bit, then I get a "too many redirects" error. In the logs, I see a long series of duplicate 302 redirects on the static-site side to that `https://accounts.youtube.com/accounts/SetSID` address, and on the Lasso side a `google userinfo body` JSON block that appears to be correct information about my account, but followed by a long series of `/auth` -> `no jwt found in request` -> `/validate` -> `/login` -> `google userinfo body` -> [loop]. I have some Lasso debug log output, too, and nothing looks like an error.

Here are what I hope are the relevant portions on my configs:

Static site `nginx.conf`:
```
http {

  server {

    listen 443 ssl http2;
    server_name foo.[domain].com;
    root /usr/share/nginx/html;

    ssl_certificate /etc/pki/nginx/server.crt;
    ssl_certificate_key /etc/pki/nginx/private/server.key;

    auth_request /validate;

    location /validate {
      proxy_pass https://lasso.[domain].com;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      auth_request_set $auth_resp_err $upstream_http_x_lasso_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_lasso_failcount;
      auth_request_set $auth_resp_jwt $upstream_http_x_lasso_jwt;
      auth_request_set $auth_resp_x_lasso_user $upstream_http_x_lasso_user;
    }

    error_page 401 = @error401;

    location @error401 {
      return 302 https://lasso.[domain].com/login?url=$scheme://$http_host$request_uri&lasso-failcount=$auth_resp_failcount&X-Lasso-Token=$auth_resp_jwt&error=$auth_resp_err;
    }

    location / {
      auth_request_set $auth_resp_x_lasso_user $upstream_http_x_lasso_user;
      proxy_set_header X-Lasso-User $auth_resp_x_lasso_user;
    }

  }

}
```
Lasso `nginx.conf`:
```
http {

  server {
    listen 443 ssl http2;
    server_name lasso.[domain].com;
    ssl_certificate /etc/pki/nginx/server.crt;
    ssl_certificate_key /etc/pki/nginx/private/server.key;
    location / {
      proxy_set_header Host lasso.[domain].com;
      proxy_pass http://127.0.0.1:9090;
    }
  }

}
```
Lasso `config.yml`:
```
lasso:
  logLevel: debug
  allowAllUsers: true
  whiteList:
  - [address]@[domain].com
  jwt:
    secret: ...
    issuer: Lasso
    maxAge: 1
    compress: true
oauth:
  provider: google
  client_id: ...
  client_secret: ...
  callback_urls:
    - https://lasso.[domain].com/auth
```
Any ideas where I might be going wrong here?

**Comment by bnfinet** [comment]
I'm traveling atm but just quickly...

Could you try turning `allowAllUsers: true` to `allowAllUsers: false`.  If you're using a whitelist, then you don't want `allowAllUsers` on.

If that doesn't work I can take a closer look tomorrow

**Comment by pmspire** [comment]
Hi Ben, thanks for responding. I tried `allowAllUsers: false`, but I still fall into the redirect loop.

I had set `allowAllUsers: true` with the thought that that, combined with `whiteList` entries, would let me authenticate a selected set of users from any domain, without setting anything under `domains`. Is using `allowAllUsers: false`, no `domains` section, and a `whiteList` section the right configuration choice for that?

**Comment by bnfinet** [comment]
'domains' are the ones that you are managing and is required in this case.
It's where the lasso cookie will be set.

**Comment by pmspire** [comment]
Aha, that's the ticket. Now my (simplified) config works fine:
```
lasso:
  domains:
    - [domain].com
  whiteList:
    - [my gmail address]
  jwt:
    secret: [secret]
    maxAge: 10080
oauth:
  provider: google
  client_id: [google oauth2 client id]
  client_secret: [google oauth2 client secret]
  callback_urls:
    - https://lasso.[domain].com/auth
```
Thank you for the clarification. And thanks for Lasso!
